// <auto-generated />
namespace IdentityTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class roles_in_dbContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(roles_in_dbContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201910281710437_roles_in_dbContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
